### ISSUE TITLE
Forest Plot of Sensitivity and Specificity like Revman 5

### ISSUE THREAD

**Issue by nelsoncarvasjr** [guido-s/diagmeta#1]
Dear Professor Guido,

I trust this message finds you well. I would like to express my gratitude for your ongoing guidance and expertise in the field of meta-analysis.

In the course of my current work, I have encountered the need to create a forest plot for a diagnostic test, where I aim to represent sensitivity and specificity. While researching this, I came across the DTAplots library, which provides similar functionality. However, I noted that the confidence intervals are calculated differently from the Clopper-Pearson method.

In light of this, I would like to inquire whether it is possible to implement this specific function in the diagmeta package, or if you could suggest alternatives that adhere to the desired method.

I greatly appreciate your attention and guidance on this matter. I am available to discuss further details and collaborate to enhance the development of this tool.

Best regards,

**Comment by guido-s** [comment]
Does the following R code produce such a forest plot?

```
library(meta)
library(grid)

m.sens <- metaprop(100 - 1:10, rep(100, 10), studlab = LETTERS[1:10])
m.spec <- metaprop(170 + 1:10, rep(200, 10), studlab = LETTERS[1:10])

ncols <- 2
nrows <- 1
firstcol <- .53

width <- 10.25
height <- 3.75

pdf("forest-sensspec.pdf", width = width, height = height)

pushViewport(viewport(
  layout = grid.layout(nrow = nrows, ncol = ncols,
                       widths = unit(c(2 * firstcol, 2 * (1 - firstcol)) *
                                     width / ncols, "inches"),
                       heights = unit(height / nrows, "inches"))))

pushViewport(viewport(layout.pos.col = 1, layout.pos.row = 1,
                      layout = grid.layout(just = "left")))

forest(m.sens, new = FALSE,
       overall = FALSE, overall.hetstat = FALSE,
       xlim = c(0.5, 1),
       leftlabs = c(NA, "TP", "n1"),
       rightlabs = c("Sens", NA),
       xlab = "Sensitivity")

popViewport()

pushViewport(viewport(layout.pos.col = 2, layout.pos.row = 1,
                      layout = grid.layout(just = "right")))

forest(m.spec, new = FALSE,
       overall = FALSE, overall.hetstat = FALSE,
       xlim = c(0.5, 1),
       leftcols = c("event", "n"),
       leftlabs = c("TN", "n2"),
       rightlabs = c("Spec", NA),
       xlab = "Specificity")

popViewport()

dev.off()

```
