### ISSUE TITLE
Negative biomarkers, log transformations and x-axis of  youden and survival plots.

### ISSUE THREAD

**Issue by vanioljantunes** [guido-s/diagmeta#3]
- [x ] feature request
  - [ x] bug report
  - [ ] support request 

## Summary

Hello! In data sets when higher levels of the test cutoff correlates with lower chances of having the disease is stated to multiply all values by -1.

> Here we assume that higher values of the biomarker indicate a greater probability for the target condition (e.g., a disease); otherwise, the poling must be changed by multiplying all values of the biomarker by -1. __help(diagmeta_)

However, in this way we can't use log transformation and therefore wouldn't be right to use the logistic distribution, right?

Unfortunately, my data does not follow a normal distribution.  Besides this, the forest plots have negative values of thresholds in youden and survival plots. Although I can turn then into opposite I'm not getting how to do the same with the regression line. It would be great therefore for:
 - Methods to select cutoffs that decrease are inversely proportional to sensitivity (fixing the problem of log transformation)
 - Method to inverse the plots (maybe just the request above could solve the issue)

Here is the example of the negative youden index
![Screenshot 2024-08-22 183919](https://github.com/user-attachments/assets/dbf151e8-ea8c-4781-bf4d-b478d0b8f9f3)

Here is the data used
[negative_cutoff.csv](https://github.com/user-attachments/files/16719303/negative_cutoff.csv)

**Comment by guido-s** [comment]
R functions `diagmeta()` and `ipd2diag()` have a new argument 'direction' which is equal to "increasing" by default.

Your data can be used with argument 'direction = "decreasing"'.

```
remotes::install_github("guido-s/diagmeta")
library("diagmeta")

dat <- readr::read_csv("negative_cutoff.csv")

# Wrong direction
ddat1 <- ipd2diag(studlab, measurement, status, data = dat)
# Correct direction
ddat2 <- ipd2diag(studlab, measurement, status, data = dat, direction = "d")

head(ddat1)
head(ddat2)

try(diagmeta(ddat1))

diagmeta(ddat2)
diagmeta(TP, FP, TN, FN, cutoff, studlab, data = ddat2, direction = "d")

```

**Comment by vanioljantunes** [comment]
Thanks for the amazing response, Dr. Schwarzer, It's indeed working perfectly!
